version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - app/.env
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]


  fastapi:
    container_name: fastapi
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db
    env_file:
      - app/.env
    volumes:
      - ./app:/app

#  ngrok:
#    image: ngrok/ngrok:latest
#    network_mode: "host"
#    restart: unless-stopped
#    container_name: ngrok
#    command:
#      - "start"
#      - "--all"
#      - "--config"
#      - "/etc/ngrok.yml"
#    volumes:
#      - ./ngrok.yml:/etc/ngrok.yml
#    ports:
#      - "4040:4040"

volumes:
  pg_data:


networks:
  backend:
