version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
    container_name: my_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db/mydatabase
    volumes:
      - ./app:/app


volumes:
  pg_data:
